#UNet config file

input:
    channels: 3

output:
    channels: 29
    labels:
        0  : unknown
        1  : road
        2  : sidewalk
        3  : parking
        4  : rail track
        5  : building
        6  : wall
        7  : fence
        8  : guard rail
        9  : bridge
        10  : tunnel
        11 : pole
        12 : polegroup
        13 : traffic light
        14 : traffic sign
        15 : vegetation
        16 : terrain
        17 : sky
        18 : person
        19 : rider
        20 : car
        21 : truck
        22 : bus
        23 : caravan
        24 : trailer
        25 : train
        26 : motorcycle
        27 : bicycle
        28 : license plate
    colors:
        0  : [  0,  0,  0]
        1  : [128, 64,128]
        2  : [244, 35,232]
        3  : [250,170,160]
        4  : [230,150,140]
        5  : [ 70, 70, 70]
        6  : [102,102,156]
        7  : [190,153,153]
        8  : [180,165,180]
        9  : [150,100,100]
        10 : [150,120, 90]
        11 : [153,153,153]
        12 : [153,153,153]
        13 : [250,170, 30]
        14 : [220,220,  0]
        15 : [107,142, 35]
        16 : [152,251,152]
        17 : [ 70,130,180]
        18 : [220, 20, 60]
        19 : [255,  0,  0]
        20 : [  0,  0,142]
        21 : [  0,  0, 70]
        22 : [  0, 60,100]
        23 : [  0,  0, 90]
        24 : [  0,  0,110]
        25 : [  0, 80,100]
        26 : [  0,  0,230]
        27 : [119, 11, 32]
        28 : [  0,  0,142] 
